before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

# We don't initialize the backend because Travis doesn't have
# credentials to connect to our AWS S3 bucket where the Terraform
# state is stored.
#
# We don't check variables because Travis doesn't have access to an
# actual zip file to use for the AWS Lambda function.
script:
  - terraform init -backend=false
  - terraform validate -check-variables=false
