language: minimal
dist: xenial
sudo: true

before_install:
  - sudo apt-get install -y shellcheck
  - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

# We don't initialize the backend because Travis doesn't have
# credentials to connect to our AWS S3 bucket where the Terraform
# state is stored.
#
# We don't check variables because Travis doesn't have access to an
# actual zip file to use for the AWS Lambda function.
script:
  - shellcheck bump_version.sh tag.sh
  - terraform init -backend=false
  - terraform validate -check-variables=false
